# Generated by Django 4.2.23 on 2025-11-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp08', '0002_eventcategory_eventmedia_eventschedule_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
    ]
