# Generated by Django 4.2.23 on 2025-11-24 12:26

from django.db import migrations, models
import django.db.models.deletion
import myapp08.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp08', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=myapp08.models.ticket_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp08.tickettier'),
        ),
    ]
