# Generated by Django 4.2.23 on 2025-11-24 12:36

from django.db import migrations, models
import myapp08.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp08', '0005_ticket_certificate_file_alter_ticket_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=myapp08.models.generate_uuid, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
